# Generated by Django 5.2.8 on 2026-01-26 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineSyncSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('friends_created', models.IntegerField(default=0)),
                ('groups_created', models.IntegerField(default=0)),
                ('group_members_created', models.IntegerField(default=0)),
                ('expenses_created', models.IntegerField(default=0)),
                ('friend_emails', models.JSONField(default=list)),
                ('group_client_ids', models.JSONField(default=list)),
                ('expense_client_ids', models.JSONField(default=list)),
                ('is_all_synced', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-processed_at'],
            },
        ),
    ]
