# Generated by Django 5.2.8 on 2026-01-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offlinesyncsession',
            name='session_id',
            field=models.CharField(max_length=100),
        ),
    ]
