# Generated by Django 5.2.8 on 2026-03-19 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_rename_member_groupmember_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('PKR', 'PKR'), ('AED', 'AED'), ('EUR', 'EUR'), ('GBP', 'GBP')], default='USD', max_length=10),
        ),
    ]
