# Generated by Django 5.2.8 on 2026-03-25 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_group_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
    ]
