# Generated by Django 5.2.8 on 2026-01-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_group_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='thumbnail',
            field=models.ImageField(default='default_group_thumbnail.jpg', upload_to='group_thumbnails'),
        ),
    ]
