# Generated by Django 5.2.8 on 2026-03-26 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_currencydropdown'),
        ('groups', '0005_alter_group_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='currency.currencydropdown'),
        ),
    ]
