# Generated by Django 5.2.8 on 2026-01-23 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_alter_group_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='client_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
