# Generated by Django 5.2.8 on 2026-10-06 05:59

from django.db import migrations, models


def approve_group_creators(apps, schema_editor):
    GroupMember = apps.get_model("groups", "GroupMember")
    creator_member_ids = list(
        GroupMember.objects.filter(user_id=models.F("group__created_by_id")).values_list("id", flat=True)
    )
    if creator_member_ids:
        GroupMember.objects.filter(id__in=creator_member_ids).update(status="approved")


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_alter_group_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='last_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='status',
            field=models.CharField(choices=[('not_requested', 'Not Requested'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_requested', max_length=20),
        ),
        migrations.RunPython(approve_group_creators, migrations.RunPython.noop),
    ]
