# Generated by Django 5.2.8 on 2025-11-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('code', models.IntegerField()),
                ('type', models.CharField(choices=[('create', 'Create'), ('forgot', 'Forgot'), ('change', 'Change')], max_length=50)),
                ('verification_token', models.CharField(max_length=200)),
                ('used', models.BooleanField(default=False)),
                ('timeout', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
