# Generated by Django 5.2.8 on 2026-01-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_invited_user',
            field=models.BooleanField(default=False),
        ),
    ]
