# Generated by Django 5.2.8 on 2025-11-20 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
        ('groups', '0002_groupmember'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expensesplit',
            old_name='member',
            new_name='participant',
        ),
        migrations.AlterUniqueTogether(
            name='expensesplit',
            unique_together={('expense', 'participant')},
        ),
    ]
