# Generated by Django 5.2.8 on 2025-11-25 08:29

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_rename_member_expensesplit_participant_and_more'),
        ('groups', '0003_rename_member_groupmember_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0.50'))])),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_items', to='groups.groupmember')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='expenses.expense')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
